development:
  adapter: mysql
  encoding: utf8
  database: finanze_development
  username: root
  password: satana
  host: localhost

test:  
  adapter: mysql
  encoding: utf8
  database: finanze_test
  username: root
  password: satana
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: finanze_production
  username: root
  password: satana
  host: localhost
