development:
  adapter: mysql
  encoding: utf8
  database: finanze_development
  username: root
  password: satana
  host: localhost

test: &TEST
   adapter: mysql
   encoding: utf8
   database: finanze_test
   username: root
   password: satana
   host: localhost

# test: &TEST
#     adapter: sqlite3 
#     database: db/test.sqlite3 
#     pool: 5 
#     timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: finanze_production
  username: root
  password: satana
  host: localhost

cucumber:
  <<: *TEST
